#! /bin/sh
# /etc/init.d/PIconnector
#

### BEGIN INIT INFO
# Provides:          PIconnector
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This service starts rpc pinger
### END INIT INFO

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    /usr/local/bin/forever start /var/apps/rpc/piconnector.js
    ;;
  stop)
    /usr/local/bin/forever stop /var/apps/rpc/piconnector.js
    ;;
  *)
    echo "Usage: /etc/init.d/PIconnector {start|stop}"
    exit 1
    ;;
esac

exit 0
